### ISSUE TITLE
Charpter 02: Tree View Muted Text

### ISSUE THREAD

**Issue by tonyerskine** [PacktPublishing/Odoo-10-Development-Essentials#2]
On line 38 of [views/todo_view.xml](https://github.com/PacktPublishing/Odoo-10-Development-Essentials/blob/master/Chapter%2002/views/todo_view.xml), it says `<tree colors="decoration-muted:is_done==True">`.  However, for me that's rendereing as, 

    <tbody>
         <tr data-id="3" class="text-muted" style="color: decoration-muted;">

...but the browsers doesn't understand, `style="color: decoration-muted;"`.  I think this an error, but perhaps I am doing something wrong.

**Comment by maximwic** [comment]
Hi.

there is a mistake in the book. This is correct definition
  `<tree decoration-muted="is_done==True">`
