### ISSUE TITLE
Errata Reported by Reader: Chapter 3: security/todo_access_rules.xml

### ISSUE THREAD

**Issue by bistaray** [PacktPublishing/Odoo-10-Development-Essentials#4]
to grant followers access to tasks as intended do the following in 
security/todo_access_rules.xml:
replace 'message_follower_ids' with 'message_partner_ids'

This is page 70 of the book.

**Comment by JVanloofsvelt** [comment]
Noticed that it is not working as well, but the suggested fix does not seem to fix it for me.
